### ISSUE TITLE
[Feature request] Support for differently sized / positioned sidebar, for example Sidebar and Window Resizer

### ISSUE THREAD

**Issue by darloth** [mouse0270/always-chat#5]
I also have the Sidebar and Window Resizer module installed (https://foundryvtt.com/packages/sidebar-resizer), and Always Chat puts the popup chat messages next to where the sidebar used to be, rather than where it actually is.  This in practice means they get obscured by the sidebar.

If you don't want to support that module specifically (or if this is easier), then it would be lovely to just be able to specify where exactly the message popups are anchored from.

For the quickest of dirtiest workarounds, maybe just adjust the popups so they draw on top of, instead of behind, the sidebar?

**Comment by mouse0270** [comment]
So this is really going to sound bad and I mean no ill will to the developer of Sidebar and Window Resizer, but this is their problem. They need to update their module so that when you resize the sidebar, they update the css variable `--sidebar-width` instead of hardcoding the width.

They are overriding the width of the css variable instead of updating its value. 

Edit: Though this design choice may have been made before the `--sidebar-width` property existed and this may be why the developer chose this method. However, I still believe it's best for their module to update the variable as it will provide better compatibility with other modules using that variable.

**Comment by mouse0270** [comment]
@darloth however if there is a module that moves the sidebar other than this module, please open a new issue as that may require me to look more into this.

**Comment by darloth** [comment]
Nope, I understand that.  If the sidebar isn't where it says it is, that is indeed not your problem.  Would you be open to a separate feature request that's "I want to put the chat popups arbitrarily anywhere onscreen" ?

**Comment by mouse0270** [comment]
Oh, I am open to any feature request, the only issue with this is, technically these two modules should work fine if the other module correctly updates the css variable. I could patch this on my end but it would be best to be resolved in that module as it would prevent other compatibility issues.

Just open a new issue for this and make sure you elaborate by "arbitrarily anywhere", do you want to be able to drag it around or you want to position it in a corner? Do you want the animations to change based on where its positioned? How do you want to position it?
